import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import { Geist } from 'next/font/google'
import '~/styles/globals.css'

import { ThemeProvider } from '~/components/ThemeProvider'

import { TRPCReactProvider } from '~/trpc/react'

export const metadata: Metadata = {
  title: 'Twenty Two AI',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
})

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang='en' className={`${geist.variable}`} suppressHydrationWarning>
        <body>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
            <main className='min-h-screen bg-[url("/images/light-background.svg")] bg-center bg-cover dark:bg-[url("/images/dark-background.svg")]'>
              <TRPCReactProvider>{children}</TRPCReactProvider>
            </main>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
